version: "3"
services:
  hub:
    image: selenium/hub:4.3.0
    ports:
      - "4444:4444" #it could be anything

  chrome:
    image: selenium/node-chrome:4.3.0
    shm_size: '1g'
    depends_on:
      - hub
    environment:
      - SE_EVENT_BUS_HOST=hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443

  firefox:
    image: selenium/node-firefox:4.3.0
    shm_size: '1g' #avoid firefox out of memory > crash :: shared memory
    depends_on:
      - hub
    environment:
      - SE_EVENT_BUS_HOST=hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443